Products = {
    ["normal"] = {
        { name = "tosti", price = 2, amount = 50, },
        { name = "water_bottle", price = 2, amount = 50, },
        { name = "kurkakola", price = 2, amount = 50, },
        { name = "twerks_candy", price = 2, amount = 50, },
        { name = "snikkel_candy", price = 2, amount = 50, },
        { name = "sandwich", price = 2, amount = 50, },
        { name = "beer", price = 7, amount = 50, },
        { name = "whiskey", price = 10, amount = 50, },
        { name = "vodka", price = 70000, amount = 50, },
        { name = "bandage", price = 100, amount = 50, },
        { name = "lighter", price = 2, amount = 50, },
        { name = "rolling_paper", price = 2, amount = 5000,  },
    },
    ["bar"] = {
        { name = "water_bottle", price = 2, amount = 50, },
        { name = "beer", price = 7, amount = 50, },
        { name = "whiskey", price = 10, amount = 50, },
        { name = "vodka", price = 70000, amount = 50, },
    },
    ["hardware"] = {
        { name = "lockpick", price = 200, amount = 50, },
        { name = "weapon_wrench", price = 250, amount = 250, },
        { name = "weapon_hammer", price = 250, amount = 250, },
        { name = "weapon_bat", price = 500, amount = 50,  requiredGang = { "lostmc" } },  -- Gang only options in stores
        { name = "repairkit", price = 250, amount = 50,  requiredJob = { ["mechanic"] = 0, ["police"] = 0 } },
        { name = "screwdriverset", price = 350, amount = 50, },
        { name = "phone", price = 850, amount = 50, },
        { name = "radio", price = 250, amount = 50, },
        { name = "binoculars", price = 50, amount = 50, },
        { name = "firework1", price = 50, amount = 50, },
        { name = "firework2", price = 50, amount = 50, },
        { name = "firework3", price = 50, amount = 50, },
        { name = "firework4", price = 50, amount = 50, },
        { name = "fitbit", price = 400, amount = 150, },
        { name = "cleaningkit", price = 150, amount = 150, },
        { name = "advancedrepairkit", price = 500, amount = 50,  requiredJob = { ["mechanic"] = 0 } },
        { name = "screwdriver", price = 450, amount = 150, },
        { name = "wd40", price = 550, amount = 150, },
        { name = "blowtorch", price = 850, amount = 50, },
    },
    ['patoche_gas_station'] = {
        {name = 'lockpick',          price = 250, amount = 50, },
        {name = 'weapon_wrench',     price = 350, amount = 250,},
        {name = 'repairkit',         price = 450, amount = 50, },
        {name = 'screwdriverset',    price = 250, amount = 50, },
        {name = 'cleaningkit',       price = 150, amount = 150,},
    },
    ["weedshop"] = {
        { name = "weedplant_seedm", price = 1250, amount = 10, },
        { name = "weedplant_seedf", price = 1450, amount = 10, },
        { name = "weedplant_branch", price = 750, amount = 5, },
        { name = "weedplant_weed", price = 850, amount = 5, },
        { name = "plant_tub", price = 150, amount = 25, },
        { name = "empty_watering_can", price = 50, amount = 50, },
        { name = "keya", price = 8500, amount = 5, },
        { name = "joint", price = 80, amount = 100, },
    },
    ["gearshop"] = {
        { name = "diving_gear", price = 2500, amount = 10, },
        { name = "jerry_can", price = 200, amount = 50, },
    },
    ["leisureshop"] = {
        { name = "parachute", price = 2500, amount = 10, },
        { name = "binoculars", price = 50, amount = 50, },
        { name = "diving_gear", price = 2500, amount = 10, },
    },
    ["weapons"] = {
        { name = "weapon_knife", price = 250, amount = 250, },
        { name = "weapon_bat", price = 250, amount = 250, },
        { name = "weapon_hatchet",price = 250, amount = 250,  requiredJob = { ["mechanic"] = 0, ["police"] = 0 } },
        { name = "weapon_pistol", price = 2500, amount = 5, requiresLicense = {"weapon"}, requiresItem = {"weaponlicense"} },
        { name = "weapon_snspistol", price = 1500, amount = 5, requiresLicense = {"weapon"}, requiresItem = {"weaponlicense"} },
        { name = "weapon_vintagepistol", price = 4000, amount = 5, requiresLicense = {"weapon", "hunting"}, requiresItem = {"weaponlicense", "huntinglicense"} },
        { name = "pistol_ammo", price = 250, amount = 250,  requiresLicense = {"weapon"}, requiresItem = {"weaponlicense"} },
    },
    ["coffeeplace"] = {
        { name = "coffee", price = 5, amount = 500 },
        { name = "lighter", price = 2, amount = 50 },
    },
    ["casino"] = {
        { name = 'casinochips', price = 1, amount = 999999 },
    },
    ["vending"] = {
        { name = "water_bottle", price = 100, amount = 25, },
        { name = "kurkakola", price = 100, amount = 25, },
        { name = "twerks_candy", price = 100, amount = 25, },
        { name = "snikkel_candy", price = 100, amount = 25, },
    },
    ["blackmarket"] = {
        { name = "phonehacker", price = 25000, amount = 3 },
        { name = "washcoin", price = 4500, amount = 15 },
    },
}